### ISSUE TITLE
No action or candidate selected

### ISSUE THREAD

**Issue by Blade6570** [waymondo/frog-jump-buffer#23]
I can switch between buffers but whenever I try to select A, M, R, P it shows this message and does nothing. Previously it was working fine. 

Frog menu detects what key I am pressing but something is happening after that. I am on emacs-27.2 linux. I have ivy-icons installed (if it has anything to do with this) 
Please help

**Comment by waymondo** [comment]
I'm not sure what you encountering, I can't reproduce your issue. I don't have `all-the-icons-ivy` installed though. Can you try uninstalling to see that makes a difference?

**Comment by aktiur** [comment]
For information, I get the exact same issue as soon as I require `all-the-icons-ivy` (icons appear correctly, I just get the same message and the modal disappearing whenever selecting one of the filters or 0)

**Comment by velppa** [comment]
Same for me, `all-the-icons-ivy` prevents filters from work, "No action or candidate selected".

**Comment by xwl** [comment]
With latest version, my config (https://github.com/waymondo/frog-jump-buffer/issues/17) also didn't work, but just the fallback doesn't work any more.

It seems it has something to do with the latest commit: https://github.com/waymondo/frog-jump-buffer/commit/3481626cccea8e77e4eee79b05f99c9171559f7b As soon as i revert the change, everything is fine again. 

As for the issue the commit tried to solve, i highly doubt the user had called toggle-debug-on-error.. So not a bug at all.

**Comment by waymondo** [comment]
I'm not sure what's going on here but I still can't reproduce. When I install `all-the-icons-ivy`, I don't even see icons.

Version info:
GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin20.3.0, NS appkit-2022.30 Version 11.2.3 (Build 20D91))
 of 2021-07-13

`frog-read` version: 0.2.11
`avy` version: 0.5.0
`all-the-icons-ivy` version: 0.5.0

Simple `use-package` declaration:
```
(use-package all-the-icons-ivy
  :init (add-hook 'after-init-hook 'all-the-icons-ivy-setup))

(use-package frog-jump-buffer
  :chords
  (";a" . frog-jump-buffer))
```

![image](https://user-images.githubusercontent.com/923418/128740724-d147d2ea-88b4-4179-b3bc-9a5a478f56ed.png)

I can confirm that `frog-jump-buffer-iconify-buffer-names` is using the `all-the-icons-ivy` transformers, which returns long lists of fontified strings for the buffer names, instead of using plain strings.

I don't see how [3481626](https://github.com/waymondo/frog-jump-buffer/commit/3481626cccea8e77e4eee79b05f99c9171559f7b) would have introduced a regression here either. Both before and after the change, `res` would be `nil`, which would prevent properly executing the action on the candidate. I would expect different symptoms for the same underlying problem.

Since this seems directly tied to `all-the-icons-ivy`, I am going to disable auto-enabling support just based on the presence of `(featurep 'all-the-icons-ivy)` and put it behind a `defcustom`.

If someone can better identify how an action candidate fails to select a fontified buffer name, please feel free to assist.
