### ISSUE TITLE
Option to not alter frog-menu-display-option-alist

### ISSUE THREAD

**Issue by noctuid** [waymondo/frog-jump-buffer#25]
It would be nice if there was an option to use `frog-menu-display-option-alist` instead of changing it.

**Comment by waymondo** [comment]
Can you elaborate what you are trying to accomplish?

**Comment by waymondo** [comment]
Can you elaborate what you are trying to accomplish?

You can customize the `frog-jump-buffer` posframe function separately from the default `avy-window` handler of `frog-menu`, but it does already share the same default value of `posframe-poshandler-point-bottom-left-corner`.

**Comment by noctuid** [comment]
I use a side window instead of a child frame with frog-menu. I have `frog-menu-type-function` set to return `avy-side-window`, but since frog-jump-buffer completely replaces `frog-menu-display-option-alist`, my custom side window configuration isn't used. I'd prefer if there was a setting to not touch `frog-menu-display-option-alist` or even better if frog-jump-buffer copied `frog-menu-display-option-alist` and only changed it for `avy-posframe`, so that any other user configuration was left as-is.

**Comment by waymondo** [comment]
I would like to keep the variable separate for `frog-jump-buffer-posframe-handler`, since I like to have the default `frog-menu` handler be at point, but the `frog-jump-buffer` window to be centered in the frame.

That said, I see the issue of your custom `avy-side-window` handler not being used. Pushing a fix for that now.

**Comment by noctuid** [comment]
Thanks!
